### ISSUE TITLE
Outdated reference to godep -save=false in README.md / Overview

### ISSUE THREAD

**Issue by dmitris** [robfig/glock#22]
Overview in README.md says: ```Glock is similar to "godep -copy=false"```.   However, godep no longer supports the -copy=false parameter:

```
$ godep save -copy=false
godep: flag unsupported: -copy=false
Usage: godep save [-r] [packages]

Run 'godep help save' for help.
```

See also:
*  https://github.com/tools/godep/blob/master/save.go#L65
*  "Making godep save always copy code" proposal: https://docs.google.com/document/d/1Dxo9PHfNVETus0UCAuviysZZAr2Hv_vPBMK1-9jBU4M/edit#heading=h.x62avzkxk8v8 
*  https://github.com/tools/godep/pull/118

It would be good to update the overview (possibly just remove the sentence and reference to godep).

**Comment by robfig** [comment]
Thanks for the note!
