### ISSUE TITLE
Add post-rewrite hook

### ISSUE THREAD

**Issue by bdarnell** [robfig/glock#23]
The git hooks installed by `glock install` apply to pulls but not to rebases (consider `git fetch; git rebase origin//master`). A `post-rewrite` hook is needed for more comprehensive coverage. (For that matter, I'd also argue that switching branches with `git checkout` should trigger a `glock sync`)

**Comment by robfig** [comment]
Thanks for pointing that out, as long as it's easy to get the log of changes between the two commits it should be easy to the post-rewrite hook...  pull requests accepted of course :)

I think syncing on every checkout would be a little bit overkill though - changing dependency versions between branches happens pretty infrequently, at least in my normal work.

**Comment by bdarnell** [comment]
We're testing a post-rewrite hook here: https://github.com/cockroachdb/cockroach/blob/172d47bbc808af1f986bb7cd257b2c310dd2ef63/githooks/post-rewrite. I'll send a PR once we've had a little more experience with it.

Changing versions between branches doesn't happen frequently, but it does happen and when it does it often breaks the build unless you manually sync. An extra `git log` call per checkout seems like a small price to pay to me.

**Comment by robfig** [comment]
Cool!

Oh, I understood your suggestion to be to blindly glock sync on every checkout.  If it's only when there was actually a change to the GLOCKFILE like the other operations, I agree
