### ISSUE TITLE
Support for Mercurial, Bazaar, Subversion is incomplete and undocumented

### ISSUE THREAD

**Issue by rickb777** [robfig/glock#26]
Evidently, Git is fully supported by Glock.

After a quick scan through the source code, it looks like there is some incomplete support for other VCS. The vcs.go file mentions git, hg, bzr and svn.

However, I got the feeling that the hook install only works for Git. Is that correct?

Are you planning to add support for other VCS? (I'm using Mercurial as it happens)

Some dependencies will come in their own VCS other than Git.  Is the rest of Glock (excluding the Git hook) going to work ok?

Perhaps the readme could summarise the current status.

Thanks,
Rick

**Comment by robfig** [comment]
That's correct, only git is supported for "glock install" -- I would welcome a pull request for mercurial support, assuming there is an analogous mechanism to git hooks. 

For fetching and updating dependencies, all VCS's are supported.  I'll look at updating the README. 

Thanks!
