### ISSUE TITLE
glock: command not found

### ISSUE THREAD

**Issue by mikeumus** [robfig/glock#31]
I'm trying to get [itsabot/abot](https://github.com/itsabot/abot) setup but I am getting `glock: command not found` on step 3 of abot's setup:

> You can install Abot via Go:
> ``` bash
> $ go get github.com/itsabot/abot
> $ cd $GOPATH/src/github.com/itsabot/abot
> $ cmd/setup.sh
> $ abot server
> ```

When I run `cmd/setup.sh` I get this:

``` bash
mikeumus:~/workspace/src/github.com/itsabot/abot (master) $ cmd/setup.sh
    [ok] checking for go binary
    [ok] checking GOPATH
    [ok] installing dependency manager
   [err] syncing dependencies

failed cmd:
         glock sync 'github.com/itsabot/abot'

bash: glock: command not found
```

This is likely some env var for go or glock that's off. I did run `go get glock` to no avail: 

``` bash
mikeumus:~/workspace $ go get github.com/robfig/glock
mikeumus:~/workspace $ glock
bash: glock: command not found
```

I'm attempting to get this setup in Cloud 9 IDE and the workspace is here:
- https://c9.io/mikeumus/abot-trial 

Please feel free to provide me your Cloud9 username and I'll grant you access to the workspace. 
Thank you for any feedback or ideas.

**Comment by chamoda** [comment]
I'm having the same issue

**Comment by NassarX** [comment]
having same issue with abot's setup and glock too

**Comment by kaminskypavel** [comment]
+1

**Comment by scdickson** [comment]
I solved it. Make sure in your PATH environment variable, you have the path to your go/bin directory. This is where abot and glock are installed. In my case, it's:

export PATH=$PATH:/home/ubuntu/go/bin

**Comment by chamoda** [comment]
I can confirm @scdickson's solution is working. Thanks

**Comment by mikeumus** [comment]
Good one @scdickson. In C9 it's `/home/ubuntu/workspace/bin/` for default C9 workspaces but Cloud9 falls over again in abot's psql commands in the [`cmd/setup.sh`](https://github.com/itsabot/abot/blob/master/cmd/setup.sh#L107) script from it's [nested postgres nature](https://community.c9.io/t/setting-up-postgresql/1573). I've posted the [issue on the C9 Community forum](https://community.c9.io/t/glock-command-not-found/4078) but for the purposes of this error, @scdickson's got it solved. Thanks to you :bow:.

**Comment by NassarX** [comment]
it works now

**Comment by rajkotraja** [comment]
i am having same issue, can anyone help, i m trying to install on Ubuntu 12.04 

Thank you
root@localhost:~/work/src/github.com/robfig/glock# cd $GOPATH/src/github.com/its
abot/abot
root@localhost:~/work/src/github.com/itsabot/abot# cmd/setup.sh

* [starting] ***********************************************************

    [ok] checking for go binary
    [ok] checking GOPATH
    [ok] installing dependency manager
   [err] syncing dependencies

   [cmd] glock sync 'github.com/itsabot/abot'

bash: glock: command not found
root@localhost:~/work/src/github.com/itsabot/abot# export GOPATH=$PATH:/usr/loca
l/go/bin
root@localhost:~/work/src/github.com/itsabot/abot# cmd/setup.sh

* [starting] ***********************************************************

    [ok] checking for go binary
    [ok] checking GOPATH
    [ok] installing dependency manager
   [err] syncing dependencies

   [cmd] glock sync 'github.com/itsabot/abot'

bash: glock: command not found
root@localhost:~/work/src/github.com/itsabot/abot# cd $GOPATH
-bash: cd: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/gam
es:/usr/local/go/bin:/home/ubuntu/go/bin:/usr/local/go/bin:/usr/local/go/bin:/us
r/local/go/bin:/usr/local/go/bin: No such file or directory
root@localhost:~/work/src/github.com/itsabot/abot# export GOPATH=/usr/local/go/b
in
root@localhost:~/work/src/github.com/itsabot/abot# cd $GOPATH
root@localhost:/usr/local/go/bin# go get github.com/itsabot/abot
# github.com/jmoiron/sqlx
src/github.com/jmoiron/sqlx/bind.go:142: undefined: strings.IndexByte
root@localhost:/usr/local/go/bin#  cd $GOPATH/src/github.com/itsabot/abot
root@localhost:/usr/local/go/bin/src/github.com/itsabot/abot# cmd/setup.sh

* [starting] ***********************************************************

    [ok] checking for go binary
    [ok] checking GOPATH
    [ok] installing dependency manager
   [err] syncing dependencies

   [cmd] glock sync 'github.com/itsabot/abot'

bash: glock: command not found
root@localhost:/usr/local/go/bin/src/github.com/itsabot/abot# abot server
No command 'abot' found, did you mean:
 Command 'rbot' from package 'rbot' (universe)
abot: command not found
root@localhost:/usr/local/go/bin/src/github.com/itsabot/abot#
