### ISSUE TITLE
Unable to install glock

### ISSUE THREAD

**Issue by RYOHOI** [robfig/glock#32]
After doing this:
`go get github.com/robfig/glock`

Terminal still says command not found.

I'm trying to install [Abot](https://github.com/itsabot/abot/wiki/Getting-Started).

**Comment by lipsumar** [comment]
same here

**Comment by HighDensityAwesome** [comment]
I am having this problem also! I have been able to fix all other errors however glock must not be installing properly because after this:
`go get github.com/robfig/glock` 
I still get the error saying that command is not found.
Please help! I think perhaps it could be an issue with glock not being in the path perhaps, I am unsure

**Comment by egtann** [comment]
Guys, this is not a glock issue. You haven't configured your Go install correctly, since $GOPATH/bin is missing from your $PATH.

**Comment by RYOHOI** [comment]
I don't think so, I have these 2 lines in my `.profile`
![Uploading terminal.png…]()

**Comment by RYOHOI** [comment]
Still waiting for the solution...

**Comment by egtann** [comment]
What's the output of `echo $PATH`

Where is the glock binary on your system? `find / -name "glock" 2>/dev/null | grep glock`

**Comment by njaremko** [comment]
@RYOHOI 
What OS are you using?
Have you checked the $GOPATH/bin folder to see if there's a glock executable?

**Comment by RYOHOI** [comment]
echo $PATH output:

`/opt/local/bin:/opt/local/sbin:/Users/Rio/.rvm/gems/ruby-2.1.1/bin:/Users/Rio/.rvm/gems/ruby-2.1.1@global/bin:/Users/Rio/.rvm/rubies/ruby-2.1.1/bin:/usr/local/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/aria2/bin:/usr/local/git/bin:/usr/local/go/bin:/usr/texbin:/Users/Rio/.rvm/bin:/Users/Rio/.rvm/bin:/Users/Rio/Workspace/bashScripting/bin:/Users/Rio/Workspace/Golang/bin`

I'm on latest Yosemite.

**Comment by RYOHOI** [comment]
![screen shot 2016-04-20 at 4 13 31 pm](https://cloud.githubusercontent.com/assets/5955526/14667659/df9087ac-0712-11e6-90f8-54cf3a57e0fd.png)

**Comment by njaremko** [comment]
You should set $GOPATH in your .bashrc, and add $GOPATH/bin to your PATH

**Comment by robfig** [comment]
Bingo!
